CREATE DATABASE SDJ_PROYECTO;
USE SDJ_PROYECTO;

----DDL----
	----Tablas----
		CREATE TABLE DJS_LIBRO(
			ID_LIB INT PRIMARY KEY IDENTITY (1000,1),
			ISBN VARCHAR (18),
			TITULO_LIB VARCHAR (40),
			AUTOR_LIB VARCHAR (50),
			EDITORIAL_LIB VARCHAR (30),
			ESTANTE_LIB INT,
			ID_EDIF_FK INT FOREIGN KEY REFERENCES DJS_EDIFICIO(ID_EDIF)
		);
		CREATE TABLE DJS_USUARIO(
			ID_US INT PRIMARY KEY IDENTITY (2000,1),
			NOMBRE_US VARCHAR (50),
			FECHA_NAC_US VARCHAR (10),
			CORREO_US VARCHAR (30),
			TELEFONO_US VARCHAR (12),
			FK_ID_EDIF INT FOREIGN KEY REFERENCES DJS_EDIFICIO(ID_EDIF),
		);
		CREATE TABLE DJS_PRESTAMO(
			ID_PREST INT PRIMARY KEY IDENTITY (3000,1),
			FECHA_ACTUAL_PREST VARCHAR (10),
			FECHAR_DEV_PREST VARCHAR (10),
			ID_USUARIO INT FOREIGN KEY REFERENCES DJS_USUARIO(ID_US),
			FK_ID_LIB INT FOREIGN KEY REFERENCES DJS_LIBRO(ID_LIB),
		);
		CREATE TABLE DJS_EDIFICIO(
			ID_EDIF INT PRIMARY KEY IDENTITY (4000,1),
			NOM_EDIF VARCHAR (20),
			DIRECCION_EDIF VARCHAR (50),
			TELEFONO_EDIF VARCHAR (12),
			CORREO_EDIF VARCHAR (30)
		);

		CREATE TABLE USUARIO_INICIO (
			ID_login int primary key identity (1,1),
			USUARIO VARCHAR (20),
			PASS	VARCHAR (15),
			);

		Create TABLE Inicio_sesion (
			ID_inicio int primary key identity (1,1),
			US VARCHAR (20),
			PASS	VARCHAR (15),
			NIVEL VARCHAR (15)
		);

		select*from USUARIO_INICIO
		CREATE VIEW CV_EDIF_UP AS(
			SELECT NOM_EDIF, TELEFONO_EDIF, CORREO_EDIF
			FROM DJS_EDIFICIO);

			SELECT*FROM CV_EDIF_UP
			select*from DJS_EDIFICIO
			select*from DJS_LIBRO

	INSERT DJS_EDIFICIO (NOM_EDIF,DIRECCION_EDIF, TELEFONO_EDIF, CORREO_EDIF)
	VALUES ('Edificio Norte', 'Av.ticoman 1', '0000011111', 'edif_nort@gmail.com'
	);
	INSERT DJS_EDIFICIO (NOM_EDIF,DIRECCION_EDIF, TELEFONO_EDIF, CORREO_EDIF)
	VALUES ('Edificio Sur', 'Periferico', '5533779911', 'edif_sur@gmail.com'
	);
	INSERT DJS_EDIFICIO (NOM_EDIF,DIRECCION_EDIF, TELEFONO_EDIF, CORREO_EDIF)
	VALUES ('Edificio Este', 'Av.Tlahuac', '3366991212', 'edif_este@gmail.com'
	);
	INSERT DJS_EDIFICIO (NOM_EDIF,DIRECCION_EDIF, TELEFONO_EDIF, CORREO_EDIF)
	VALUES ('Edificio Oeste', 'Av.México', '9988776655', 'edif_o@gmail.com'
	);
	INSERT DJS_EDIFICIO (NOM_EDIF,DIRECCION_EDIF, TELEFONO_EDIF, CORREO_EDIF)
	VALUES ('Edificio Centro', 'Reforma 02', '0011223344', 'edif_cent@gmail.com'
	);



	INSERT DJS_LIBRO (ISBN,TITULO_LIB, AUTOR_LIB, EDITORIAL_LIB, ESTANTE_LIB,ID_EDIF_FK)
	VALUES ('9788420477886','Cadaver Exquisito','Agustina Bazterrica','Alfaguara', 11,4001),
			('9788418395024','Carmilla','J.Sheridan Le Fanu','Editorial Alma', 13, 4002),
			('9788448006983','Buenos Presagios','Terry Pratchett','Timun', 1, 4003),
			('9780141331461','The demigod files','Rick Riordan','Penguin', 5,4004),
			('9786070733697','Starters','Lissa Price','Destino', 5,4005),
			('9789700771489','Crimen y castigo','Fiódor Dostoyevski','Porrua', 5, 4001);
	
	select*from DJS_LIBRO

	SELECT*FROM DJS_USUARIO
	INSERT DJS_USUARIO  (NOMBRE_US, FECHA_NAC_US, CORREO_US, TELEFONO_US)
	VALUES ('Pedro Sanchez', '01/02/1980','pedro1@gmail.com','55110022' 
	);
	INSERT DJS_USUARIO (NOMBRE_US, FECHA_NAC_US, CORREO_US, TELEFONO_US)
	VALUES ('Lucero Gomez', '28/02/1970','l_gomez@gmail.com','0011223344'
	);
	INSERT DJS_USUARIO (NOMBRE_US, FECHA_NAC_US, CORREO_US, TELEFONO_US)
	VALUES ('Angelica Jimenez', '01/03/1983','angjim03@gmail.com','4433221100'
	);
	INSERT DJS_USUARIO (NOMBRE_US, FECHA_NAC_US, CORREO_US, TELEFONO_US)
	VALUES ('Percy Jackson', '16/08/2002','pjackson@gmail.com','9988776655'
	);
	INSERT DJS_USUARIO (NOMBRE_US, FECHA_NAC_US, CORREO_US, TELEFONO_US)
	VALUES ('Fernanda Jimenez', '23/08/2014','ferjim@gmail.com','5566778899'
	);

	select*from DJS_PRESTAMO
	select*from DJS_LIBRO

	INSERT DJS_PRESTAMO 
	VALUES ('20-05-2025','04-06-2025', 2000,1005
	);
	INSERT DJS_PRESTAMO 
	VALUES ('21-05-2025','05-06-2025', 2001,1004
	);
	INSERT DJS_PRESTAMO
	VALUES ('22-05-2025','06-06-2025', 2002,1003
	);
	INSERT DJS_PRESTAMO 
	VALUES ('23-05-2025','07-06-2025', 2003,1002
	);
	INSERT DJS_PRESTAMO 
	VALUES ('24-05-2025','08-06-2025', 2004,1001
	);

	INSERT USUARIO_INICIO
	VALUES ('Admin', '12345'),
			('Invitado' , '00000');
	INSERT Inicio_sesion
	VALUES ('Admin', '123', 'ADMINISTRADOR');
	INSERT Inicio_sesion
	VALUES ('invitado', '321', 'INVITADO');

	SELECT*FROM DJS_EDIFICIO
	SELECT*FROM DJS_LIBRO
	SELECT*FROM DJS_PRESTAMO
	SELECT*FROM DJS_USUARIO


CREATE TRIGGER CT_ELIMINAR_LIBRO
ON DJS_LIBRO
INSTEAD OF DELETE
AS 
UPDATE DJS_PRESTAMO
SET FK_ID_LIB = NULL
FROM deleted
WHERE FK_ID_LIB = ID_LIB

DELETE
FROM DJS_LIBRO
FROM deleted
WHERE DJS_LIBRO.ID_LIB=deleted.ID_LIB;

CREATE TRIGGER CT_ELIMINAR_USUARIO
ON DJS_USUARIO
INSTEAD OF DELETE
AS 
UPDATE DJS_PRESTAMO
SET ID_USUARIO = NULL
FROM deleted
WHERE ID_USUARIO = ID_US

DELETE
FROM DJS_USUARIO
FROM deleted
WHERE DJS_USUARIO.ID_US=deleted.ID_US;

CREATE TRIGGER CT_ELIMINAR_EDIFICIO
ON DJS_EDIFICIO
INSTEAD OF DELETE
AS 
UPDATE DJS_LIBRO
SET ID_EDIF_FK = NULL
FROM deleted
WHERE ID_EDIF_FK = ID_EDIF
UPDATE DJS_USUARIO
SET FK_ID_EDIF = NULL
FROM deleted
WHERE FK_ID_EDIF = ID_EDIF

DELETE
FROM DJS_EDIFICIO
FROM deleted
WHERE DJS_EDIFICIO.ID_EDIF=deleted.ID_EDIF;

 DELETE FROM DJS_PRESTAMO WHERE ID_PREST= 3007;
 DELETE FROM DJS_USUARIO WHERE ID_US= 2003;

 select*from DJS_USUARIO


 SELECT NIVEL FROM USUARIO WHERE USUARIO = 'Admin' AND PASS = '12345'

 SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'USUARIO_INICIO'

 SELECT NIVEL FROM SDJ_PROYECTO WHERE TABLE_NAME = 'USUARIO_INICIO'
 SELECT*FROM USUARIO_INICIO
 select*from Inicio_sesion

 select*from DJS_EDIFICIO
 select*from DJS_USUARIO
 select*from DJS_LIBRO
 select*from DJS_PRESTAMO