CREATE DATABASE DJS_EQUIPO1_PROYECTO;
USE DJS_EQUIPO1_PROYECTO;

----DDL----
	----Tablas----
		CREATE TABLE DJS_LIBRO(
			ID_LIB INT PRIMARY KEY IDENTITY (1,1),
			ISBN VARCHAR (18),
			TITULO_LIB VARCHAR (40),
			AUTOR_LIB VARCHAR (50),
			EDITORIAL_LIB VARCHAR (30),
			ESTANTE_LIB INT
		);
		CREATE TABLE DJS_USUARIO(
			ID_US INT PRIMARY KEY IDENTITY (3,3),
			NOMBRE_US VARCHAR (50),
			FECHA_NAC_US VARCHAR (10),
			CORREO_US VARCHAR (30),
			TELEFONO_US VARCHAR (12)
		);
		CREATE TABLE DJS_PRESTAMO(
			ID_PREST INT PRIMARY KEY IDENTITY (5,5),
			FECHA_ACTUAL_PREST VARCHAR (10),
			FECHAR_DEV_PREST VARCHAR (10),
			ID_USUARIO INT FOREIGN KEY REFERENCES DJS_USUARIO(ID_US)
		);
		drop TABLE DJS_EDIFICIO(
			ID_EDIF INT PRIMARY KEY IDENTITY (2,2),
			NOM_EDIF VARCHAR (20),
			DIRECCION_EDIF VARCHAR (50),
			TELEFONO_EDIF VARCHAR (12),
			CORREO_EDIF VARCHAR (30)
		);
		CREATE TABLE DJS_EDIFICIO_LIBRO(
			ID_LIB_FK INT FOREIGN KEY REFERENCES DJS_LIBRO(ID_LIB),
			ID_EDIF_FK INT FOREIGN KEY REFERENCES DJS_EDIFICIO(ID_EDIF)
		);
		CREATE TABLE DJS_EDIFICIO_USUARIO(
			FK_ID_EDIF INT FOREIGN KEY REFERENCES DJS_EDIFICIO(ID_EDIF),
			FK_ID_US INT FOREIGN KEY REFERENCES DJS_USUARIO(ID_US)
		);
		CREATE TABLE DJS_LIBRO_PRESTAMO(
			FK_ID_LIB INT FOREIGN KEY REFERENCES DJS_LIBRO(ID_LIB),
			ID_PREST_FK INT FOREIGN KEY REFERENCES DJS_PRESTAMO(ID_PREST)
		);
	----Alter table----
		ALTER TABLE DJS_LIBRO 
		ADD EJEMPLARES INT;

		ALTER TABLE DJS_USUARIO
		ADD DIRECCION VARCHAR (50);

		ALTER TABLE DJS_EDIFICIO
		ADD ENCARGADO VARCHAR (50);

		ALTER TABLE DJS_LIBRO
		ADD COSTO INT;

	----Create view----
		CREATE VIEW CV_DJS_DATOS_PESTAMO AS(
			SELECT TITULO_LIB,AUTOR_LIB,NOMBRE_US, FECHA_ACTUAL_PREST, FECHAR_DEV_PREST
			FROM DJS_LIBRO,DJS_USUARIO, DJS_PRESTAMO, DJS_LIBRO_PRESTAMO
			WHERE ID_USUARIO=ID_US AND ID_PREST_FK=ID_PREST AND FK_ID_LIB=ID_LIB
		);
		CREATE VIEW CV_DJS_USUARIOS_PRESTAMO_EDIFICIO AS(
			SELECT NOMBRE_US, FECHA_ACTUAL_PREST, FECHAR_DEV_PREST,TITULO_LIB,AUTOR_LIB, NOM_EDIF
			FROM DJS_LIBRO,DJS_USUARIO, DJS_PRESTAMO, DJS_LIBRO_PRESTAMO,DJS_EDIFICIO,DJS_EDIFICIO_LIBRO
			WHERE ID_USUARIO=ID_US AND ID_PREST_FK=ID_PREST AND FK_ID_LIB=ID_LIB AND ID_LIB_FK=ID_LIB AND ID_EDIF_FK=ID_EDIF);
		CREATE VIEW CV_USUARIOS_REGISTRADOS_EDIFICIO AS(
			SELECT NOMBRE_US, CORREO_US, TELEFONO_US, NOM_EDIF, DIRECCION_EDIF
			FROM DJS_USUARIO, DJS_EDIFICIO, DJS_EDIFICIO_USUARIO
			WHERE FK_ID_US=ID_US AND FK_ID_EDIF=ID_EDIF);
	----Create index----
		CREATE INDEX CI_DJS_UBICACION_LIBRO
		ON DJS_LIBRO (TITULO_LIB,AUTOR_LIB,ESTANTE_LIB)

----DML----
	----INSERT----
	--*Libro*--
	SELECT*FROM DJS_LIBRO
	`
	INSERT DJS_LIBRO (ISBN,TITULO_LIB, AUTOR_LIB, EDITORIAL_LIB, ESTANTE_LIB)
	VALUES ('9788420477886','Cadaver Exquisito','Agustina Bazterrica','Alfaguara', 11
	);
	INSERT DJS_LIBRO (ISBN,TITULO_LIB, AUTOR_LIB, EDITORIAL_LIB, ESTANTE_LIB)
	VALUES ('9788418395024','Carmilla','J.Sheridan Le Fanu','Editorial Alma', 13
	);
	INSERT DJS_LIBRO (ISBN,TITULO_LIB, AUTOR_LIB, EDITORIAL_LIB, ESTANTE_LIB)
	VALUES ('9788448006983','Buenos Presagios','Terry Pratchett','Timun', 1
	);
	INSERT DJS_LIBRO (ISBN,TITULO_LIB, AUTOR_LIB, EDITORIAL_LIB, ESTANTE_LIB)
	VALUES ('9780141331461','The demigod files','Rick Riordan','Penguin', 5
	);
	INSERT DJS_LIBRO (ISBN,TITULO_LIB, AUTOR_LIB, EDITORIAL_LIB, ESTANTE_LIB)
	VALUES ('9786070733697','Starters','Lissa Price','Destino', 5
	);
	INSERT DJS_LIBRO (ISBN,TITULO_LIB, AUTOR_LIB, EDITORIAL_LIB, ESTANTE_LIB)
	VALUES ('9789700771489','Crimen y castigo','Fiódor Dostoyevski','Porrua', 5
	);
	--*Usuario*--
	SELECT*FROM DJS_USUARIO
	INSERT DJS_USUARIO  (NOMBRE_US, FECHA_NAC_US, CORREO_US, TELEFONO_US)
	VALUES ('Pedro Sanchez', '01/02/1980','pedro1@gmail.com','55110022' 
	);
	INSERT DJS_USUARIO (NOMBRE_US, FECHA_NAC_US, CORREO_US, TELEFONO_US)
	VALUES ('Lucero Gomez', '28/02/1970','l_gomez@gmail.com','0011223344'
	);
	INSERT DJS_USUARIO (NOMBRE_US, FECHA_NAC_US, CORREO_US, TELEFONO_US)
	VALUES ('Angelica Jimenez', '01/03/1983','angjim03@gmail.com','4433221100'
	);
	INSERT DJS_USUARIO (NOMBRE_US, FECHA_NAC_US, CORREO_US, TELEFONO_US)
	VALUES ('Percy Jackson', '16/08/2002','pjackson@gmail.com','9988776655'
	);
	INSERT DJS_USUARIO (NOMBRE_US, FECHA_NAC_US, CORREO_US, TELEFONO_US)
	VALUES ('Fernanda Jimenez', '23/08/2014','ferjim@gmail.com','5566778899'
	);
	--*Prestamo*--
	SELECT*FROM DJS_PRESTAMO
	INSERT DJS_PRESTAMO (FECHA_ACTUAL_PREST, FECHAR_DEV_PREST, ID_USUARIO)
	VALUES ('20-05-2025','04-06-2025', 9
	);
	INSERT DJS_PRESTAMO (FECHA_ACTUAL_PREST, FECHAR_DEV_PREST, ID_USUARIO)
	VALUES ('21-05-2025','05-06-2025', 3
	);
	INSERT DJS_PRESTAMO (FECHA_ACTUAL_PREST, FECHAR_DEV_PREST, ID_USUARIO)
	VALUES ('22-05-2025','06-06-2025', 6
	);
	INSERT DJS_PRESTAMO (FECHA_ACTUAL_PREST, FECHAR_DEV_PREST, ID_USUARIO)
	VALUES ('23-05-2025','07-06-2025', 12
	);
	INSERT DJS_PRESTAMO (FECHA_ACTUAL_PREST, FECHAR_DEV_PREST, ID_USUARIO)
	VALUES ('24-05-2025','08-06-2025', 15
	);
	--*Edificio*--
	SELECT*FROM DJS_EDIFICIO
	INSERT DJS_EDIFICIO (NOM_EDIF,DIRECCION_EDIF, TELEFONO_EDIF, CORREO_EDIF)
	VALUES ('Edificio Norte', 'Av.ticoman 1', '0000011111', 'edif_nort@gmail.com'
	);
	INSERT DJS_EDIFICIO (NOM_EDIF,DIRECCION_EDIF, TELEFONO_EDIF, CORREO_EDIF)
	VALUES ('Edificio Sur', 'Periferico', '5533779911', 'edif_sur@gmail.com'
	);
	INSERT DJS_EDIFICIO (NOM_EDIF,DIRECCION_EDIF, TELEFONO_EDIF, CORREO_EDIF)
	VALUES ('Edificio Este', 'Av.Tlahuac', '3366991212', 'edif_este@gmail.com'
	);
	INSERT DJS_EDIFICIO (NOM_EDIF,DIRECCION_EDIF, TELEFONO_EDIF, CORREO_EDIF)
	VALUES ('Edificio Oeste', 'Av.México', '9988776655', 'edif_o@gmail.com'
	);
	INSERT DJS_EDIFICIO (NOM_EDIF,DIRECCION_EDIF, TELEFONO_EDIF, CORREO_EDIF)
	VALUES ('Edificio Centro', 'Reforma 02', '0011223344', 'edif_cent@gmail.com'
	);
	--*Edificio_Libro*--
	SELECT*FROM DJS_EDIFICIO
	SELECT*FROM DJS_LIBRO
	SELECT*FROM DJS_EDIFICIO_LIBRO
	INSERT DJS_EDIFICIO_LIBRO (ID_LIB_FK, ID_EDIF_FK)
	VALUES(1,2
	);
	INSERT DJS_EDIFICIO_LIBRO (ID_LIB_FK, ID_EDIF_FK)
	VALUES(2,4
	);
	INSERT DJS_EDIFICIO_LIBRO (ID_LIB_FK, ID_EDIF_FK)
	VALUES(3,6
	);
	INSERT DJS_EDIFICIO_LIBRO (ID_LIB_FK, ID_EDIF_FK)
	VALUES(4,8
	);
	INSERT DJS_EDIFICIO_LIBRO (ID_LIB_FK, ID_EDIF_FK)
	VALUES(5,10
	);
	--*Edificio_Usuario*--
	SELECT*FROM DJS_EDIFICIO
	SELECT*FROM DJS_USUARIO
	SELECT*FROM DJS_EDIFICIO_USUARIO
	INSERT DJS_EDIFICIO_USUARIO (FK_ID_EDIF,FK_ID_US)
	VALUES (2,3
	);
	INSERT DJS_EDIFICIO_USUARIO (FK_ID_EDIF,FK_ID_US)
	VALUES (4,6
	);
	INSERT DJS_EDIFICIO_USUARIO (FK_ID_EDIF,FK_ID_US)
	VALUES (6,9
	);
	INSERT DJS_EDIFICIO_USUARIO (FK_ID_EDIF,FK_ID_US)
	VALUES (8,12
	);
	INSERT DJS_EDIFICIO_USUARIO (FK_ID_EDIF,FK_ID_US)
	VALUES (10,15
	);
	--*Libro_Prestamo*--
	SELECT*FROM DJS_LIBRO
	SELECT*FROM DJS_PRESTAMO
	SELECT*FROM DJS_LIBRO_PRESTAMO
	INSERT DJS_LIBRO_PRESTAMO (FK_ID_LIB, ID_PREST_FK)
	VALUES (1,5
	);
	INSERT DJS_LIBRO_PRESTAMO (FK_ID_LIB, ID_PREST_FK)
	VALUES (2,10
	);
	INSERT DJS_LIBRO_PRESTAMO (FK_ID_LIB, ID_PREST_FK)
	VALUES (3,15
	);
	INSERT DJS_LIBRO_PRESTAMO (FK_ID_LIB, ID_PREST_FK)
	VALUES (4,20
	);
	INSERT DJS_LIBRO_PRESTAMO (FK_ID_LIB, ID_PREST_FK)
	VALUES (6,25
	);

	----UPDATE----
	SELECT*FROM DJS_USUARIO
		UPDATE DJS_USUARIO
		SET DIRECCION='Av.Té'
		WHERE ID_US=3
		;
		UPDATE DJS_USUARIO
		SET DIRECCION='Av.Ticoman'
		WHERE ID_US=6
		;
		UPDATE DJS_USUARIO
		SET DIRECCION='Av.Castillo'
		WHERE ID_US=9
		;
		UPDATE DJS_USUARIO
		SET DIRECCION='Av.11'
		WHERE ID_US=12
		;
		UPDATE DJS_USUARIO
		SET DIRECCION='Calle 13'
		WHERE ID_US=15;

	SELECT*FROM DJS_LIBRO
		UPDATE DJS_LIBRO
		SET EJEMPLARES=3
		WHERE ID_LIB=1
		;
		UPDATE DJS_LIBRO
		SET EJEMPLARES=5
		WHERE ID_LIB=2
		;
		UPDATE DJS_LIBRO
		SET EJEMPLARES=10
		WHERE ID_LIB=3
		;
		UPDATE DJS_LIBRO
		SET EJEMPLARES=1
		WHERE ID_LIB=4
		;
		UPDATE DJS_LIBRO
		SET EJEMPLARES=2
		WHERE ID_LIB=5
		;
		UPDATE DJS_LIBRO
		SET EJEMPLARES=2
		WHERE ID_LIB=6
		;
	SELECT*FROM DJS_EDIFICIO
		UPDATE DJS_EDIFICIO
		SET ENCARGADO='Jose Perez'
		WHERE ID_EDIF=2
		;
		UPDATE DJS_EDIFICIO
		SET ENCARGADO='Ramiro Gonzales'
		WHERE ID_EDIF=4
		;
		UPDATE DJS_EDIFICIO
		SET ENCARGADO='Javier Contreras'
		WHERE ID_EDIF=6
		;
		UPDATE DJS_EDIFICIO
		SET ENCARGADO='Maria Perez'
		WHERE ID_EDIF=8
		;
		UPDATE DJS_EDIFICIO
		SET ENCARGADO='Mauricio Hernandez'
		WHERE ID_EDIF=10
		;

		UPDATE DJS_LIBRO
		SET COSTO =350
		WHERE ID_LIB =1;

		UPDATE DJS_LIBRO
		SET COSTO =500
		WHERE ID_LIB =2;

		UPDATE DJS_LIBRO
		SET COSTO =400
		WHERE ID_LIB =3;

		UPDATE DJS_LIBRO
		SET COSTO =350
		WHERE ID_LIB =4;

		UPDATE DJS_LIBRO
		SET COSTO =1500
		WHERE ID_LIB =5;

		UPDATE DJS_LIBRO
		SET COSTO =600
		WHERE ID_LIB =6;


	----DELETE----
	DELETE FROM DJS_LIBRO
	WHERE ID_LIB=1
	;
	DELETE FROM DJS_EDIFICIO
	WHERE ID_EDIF=10
	;
	DELETE FROM DJS_PRESTAMO
	WHERE ID_PREST=15
	;
	DELETE FROM DJS_USUARIO
	WHERE ID_US=9
	;

	----SELECT----
	SELECT TITULO_LIB,AUTOR_LIB, ESTANTE_LIB, EJEMPLARES
	FROM DJS_LIBRO
	WHERE ESTANTE_LIB= (SELECT MIN (ESTANTE_LIB) FROM DJS_LIBRO
	);
	SELECT TITULO_LIB,AUTOR_LIB, ESTANTE_LIB, EJEMPLARES, NOM_EDIF
	FROM DJS_LIBRO, DJS_EDIFICIO,DJS_EDIFICIO_LIBRO
	WHERE EJEMPLARES= (SELECT MAX (EJEMPLARES) FROM DJS_LIBRO) AND ID_LIB_FK=ID_LIB AND ID_EDIF_FK=ID_EDIF
	;
	SELECT TITULO_LIB,AUTOR_LIB, ESTANTE_LIB, EJEMPLARES, NOM_EDIF
	FROM DJS_LIBRO, DJS_EDIFICIO,DJS_EDIFICIO_LIBRO
	WHERE EJEMPLARES= (SELECT MIN (EJEMPLARES) FROM DJS_LIBRO) AND ID_LIB_FK=ID_LIB AND ID_EDIF_FK=ID_EDIF;

	CREATE VIEW DJS_VISUALIZAR_REGISTROS AS (
		SELECT ISBN, TITULO_LIB,AUTOR_LIB, EDITORIAL_LIB,ESTANTE_LIB, EJEMPLARES
		FROM DJS_LIBRO);
	
	SELECT*FROM DJS_VISUALIZAR_REGISTROS

	SELECT*FROM DJS_EDIFICIO_LIBRO
	SELECT*FROM DJS_EDIFICIO_USUARIO
	SELECT*FROM DJS_LIBRO_PRESTAMO
	SELECT*FROM DJS_EDIFICIO
	SELECT*FROM DJS_LIBRO
	SELECT*FROM DJS_PRESTAMO
	SELECT*FROM DJS_USUARIO


	--nombre edificio, nombres de los libros y nombres de los usuarios

	SELECT NOM_EDIF, TITULO_LIB, NOMBRE_US
	FROM DJS_EDIFICIO,DJS_EDIFICIO_LIBRO,DJS_LIBRO, DJS_USUARIO, DJS_EDIFICIO_USUARIO
	WHERE ID_EDIF=ID_EDIF_FK AND ID_LIB=ID_LIB_FK AND ID_EDIF=FK_ID_EDIF AND ID_US=FK_ID_US

	Create view DJS_PROMEDIO as(
	select avg(costo) as promedio_costo from DJS_LIBRO);

	SELECT TITULO_LIB AS TITULO, COSTO, promedio_costo
	FROM DJS_LIBRO, DJS_PROMEDIO

	select ID_US FROM DJS_USUARIO

	---Procedures---

	CREATE PROCEDURE CP_DJS_INSERTAR_LIBRO
		@isbn VARCHAR (18),
		@titulo VARCHAR (40),
		@autor VARCHAR (50),
		@editorial VARCHAR (30),
		@estante INT,
		@ejemplares int,
		@costo int
		AS
		INSERT INTO DJS_LIBRO (ISBN,TITULO_LIB,AUTOR_LIB,EDITORIAL_LIB,ESTANTE_LIB,EJEMPLARES,COSTO)
		VALUES (@isbn,@titulo,@autor,@editorial,@estante,@ejemplares,@costo);
	
	EXEC CP_DJS_INSERTAR_LIBRO '9788498382365', 'Percy Jackson y el mar de los monstruos', 'Rick Riordan', 'Salamandra', 6, 1,288;

	CREATE TRIGGER CT_DJS_INSERTAR
	ON DJS_LIBRO
	FOR INSERT
	AS
	INSERT INTO DJS_HISTORIAL( ID_LIBRO, FECHA, USUARIO, DESCRIPCION) 
	SELECT ID_LIB, SYSDATETIME(), USER_NAME(),'EDITADO' FROM inserted 
	SELECT * FROM DJS_LIBRO
	SELECT * FROM DJS_HISTORIAL
	SELECT* FROM inserted;


	CREATE PROCEDURE CP_DJS_ACTUALIZAR_LIBRO
		@id int,
		@estante int
		AS
		UPDATE DJS_LIBRO
		SET ESTANTE_LIB=@estante
		WHERE ID_LIB= @id;

	EXEC CP_DJS_ACTUALIZAR_LIBRO 10,5 

	CREATE TABLE DJS_HISTORIAL(
	ID_LIBRO INT,
	FECHA VARCHAR (20),
	USUARIO VARCHAR (15),
	DESCRIPCION VARCHAR (15),
	ESTANTE_ANTERIOR int 
	);
	SELECT*FROM DJS_HISTORIAL
	SELECT*FROM DJS_LIBRO


	CREATE TRIGGER CT_DJS_INSERTAR_HISTORIAL
	ON DJS_LIBRO
	FOR UPDATE
	AS
	INSERT INTO DJS_HISTORIAL( ID_LIBRO, FECHA, USUARIO, DESCRIPCION, ESTANTE_ANTERIOR) 
	SELECT inserted.ID_LIB, SYSDATETIME(), USER_NAME(),'EDITADO', deleted.ESTANTE_LIB
	FROM inserted, deleted
	SELECT * FROM DJS_LIBRO
	SELECT * FROM DJS_HISTORIAL
	SELECT* FROM inserted;



	CREATE PROCEDURE CP_DJS_SELECCIONAR_LIBRO
		@id INT
		AS
		SELECT*FROM DJS_LIBRO
		WHERE ID_LIB = @id;

	Exec CP_DJS_SELECCIONAR_LIBRO 3

	CREATE PROCEDURE CP_DJS_ELIMINAR_LIBRO
		@id int
		AS
		DELETE FROM DJS_LIBRO
		WHERE ID_LIB=@id;

	EXEC CP_DJS_ELIMINAR_LIBRO 2

	CREATE TRIGGER CT_DJS_LIBRO_ELIMINADO
	ON DJS_LIBRO
	INSTEAD OF DELETE
	AS 
	UPDATE DJS_EDIFICIO_LIBRO
	SET ID_LIB_FK = NULL
	FROM deleted
	WHERE ID_LIB_FK =ID_LIB

	UPDATE DJS_LIBRO_PRESTAMO
	SET FK_ID_LIB = NULL
	FROM deleted
	WHERE FK_ID_LIB =ID_LIB

	DELETE
	FROM DJS_LIBRO
	FROM deleted
	WHERE DJS_LIBRO.ID_LIB =deleted.ID_LIB
	
	SELECT*FROM deleted
	SELECT*FROM DJS_LIBRO
	SELECT*FROM DJS_EDIFICIO_LIBRO
	SELECT*FROM DJS_LIBRO_PRESTAMO
	
	;


	------Crear usuario------

CREATE LOGIN ADMINISTRADOR WITH PASSWORD = '12345';
CREATE USER ADMINISTRADOR FOR LOGIN ADMINISTRADOR;

/*-----Crear privilegios-----*/

USE DJS_EQUIPO1_PROYECTO
GRANT INSERT, DELETE, UPDATE, SELECT
ON DJS_LIBRO
TO ADMINISTRADOR
WITH GRANT OPTION;

REVOKE INSERT,DELETE,UPDATE,SELECT
ON DJS_LIBRO
TO ADMINISTRADOR
CASCADE;

---transaccion---

	BEGIN TRY
		BEGIN TRAN
			UPDATE DJS_LIBRO
			SET EJEMPLARES = EJEMPLARES-1
			WHERE ID_LIB = 3
			INSERT INTO DJS_HISTORIAL (ID_LIBRO,FECHA, USUARIO, DESCRIPCION)
			VALUES (2, GETDATE(),USER_NAME(), 'prestamo')
			SELECT*FROM DJS_HISTORIAL
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
	END CATCH


			CREATE TABLE DJS_HISTORIAL(
	ID_LIBRO INT,
	FECHA VARCHAR (20),
	USUARIO VARCHAR (15),
	DESCRIPCION VARCHAR (15)
	);

	S