CREATE DATABASE DJS_EJERCICIO_TRIGGER;
USE DJS_EJERCICIO_TRIGGER;

CREATE TABLE DJS_ALUMNO (
BOLETA INT PRIMARY KEY IDENTITY (1,1),
NOM_ALUMN VARCHAR (15), 
CARRERA VARCHAR (10),
DIR_ALUMN VARCHAR (15),
TEL_ALUMNO VARCHAR (10)
);

CREATE TABLE DJS_CONTROL_MOVIMIENTO(
ID_ALUMNO INT,
FECHA VARCHAR (20),
USUARIO VARCHAR (15),
DESCRIPCION VARCHAR (15)
);

SELECT * FROM DJS_ALUMNO
SELECT * FROM DJS_CONTROL_MOVIMIENTO


/*--------INSERT-------*/
CREATE PROCEDURE CP_DJS_INSERTAR_ALUMNO
@NOM_ALUMNO VARCHAR (15),
@CARRERA VARCHAR (10),
@DIR_ALUMNO VARCHAR (15),
@TEL_ALUMNO VARCHAR (10)
AS
INSERT INTO DJS_ALUMNO(NOM_ALUMN, CARRERA,DIR_ALUMN,TEL_ALUMNO)
VALUES (@NOM_ALUMNO, @CARRERA,@DIR_ALUMNO,@TEL_ALUMNO);

EXEC CP_DJS_INSERTAR_ALUMNO 'LUISITO','II','AVENIDA X', '5544332211';
EXEC CP_DJS_INSERTAR_ALUMNO 'JOSE','CI','AVENIDA Y', '5544332200';
EXEC CP_DJS_INSERTAR_ALUMNO 'PEDRO','II','AVENIDA Z', '5544332200';
EXEC CP_DJS_INSERTAR_ALUMNO 'JUAN','CI','AVENIDA A', '5566778899';


CREATE TRIGGER CT_DJS_INSERTAR_CONTROL_INSERTAR_ALUMNO
ON DJS_ALUMNO
FOR INSERT
AS
INSERT INTO DJS_CONTROL_MOVIMIENTO ( ID_ALUMNO, FECHA, USUARIO, DESCRIPCION) 
SELECT BOLETA, SYSDATETIME(), USER_NAME(),'INSERT' FROM inserted 
SELECT * FROM DJS_ALUMNO
SELECT * FROM DJS_CONTROL_MOVIMIENTO
SELECT* FROM inserted; 

/*--------UPDATE-------*/

CREATE PROCEDURE CP_DJS_UPDATE_ALUMNO
@ID_ALUMNO INT,
@TEL_ALUMNO VARCHAR (10)
AS
UPDATE DJS_ALUMNO
SET TEL_ALUMNO = @TEL_ALUMNO
WHERE BOLETA = @ID_ALUMNO;

EXEC CP_DJS_UPDATE_ALUMNO 1,'0011223344';

CREATE TRIGGER CT_DJS_UPDATE_CONTROL_UPDATE_ALUMNO
ON DJS_ALUMNO
FOR UPDATE
AS
INSERT INTO DJS_CONTROL_MOVIMIENTO ( ID_ALUMNO, FECHA, USUARIO, DESCRIPCION) 
SELECT BOLETA, SYSDATETIME(), USER_NAME(),'UPDATE' FROM inserted 
SELECT * FROM DJS_ALUMNO
SELECT * FROM DJS_CONTROL_MOVIMIENTO
SELECT* FROM inserted; 

/*--------DELETE-------*/

CREATE PROCEDURE CP_DJS_DELETE_SUCURSAL
@ID_ALUMNO INT
AS
DELETE FROM DJS_ALUMNO
WHERE BOLETA = @ID_ALUMNO;


EXEC CP_DJS_DELETE_SUCURSAL 4;

CREATE TRIGGER CT_DJS_DELETE_CONTROL_DELETE_ALUMNO
ON DJS_ALUMNO
FOR DELETE
AS
INSERT INTO DJS_CONTROL_MOVIMIENTO ( ID_ALUMNO, FECHA, USUARIO, DESCRIPCION) 
SELECT BOLETA, SYSDATETIME(), USER_NAME(),'DELETE' FROM deleted
SELECT * FROM DJS_ALUMNO
SELECT * FROM DJS_CONTROL_MOVIMIENTO
SELECT* FROM deleted; 


/*CREAR USUARIO PARA PRODUCTO, DARLE LOS 4 PRIVILEGIOS (INSERT, DELATE, UPDATE,Y EL OTRO)*/





