CREATE DATABASE RBV_PELICULA;
use RBV_PELICULA;

CREATE TABLE RBV_ACTOR_PRINCIPAL (
ID_ACT_PRINCIPAL int IDENTITY (1,1) PRIMARY KEY,
NOM_ACT_PRINCIPAL VARCHAR (20),
TEL_ACT_PRINCIPAL VARCHAR (15),
DOMICILIO VARCHAR (15)
);

CREATE TABLE RBV_EXTRA (
DNI_EXTRA int  PRIMARY KEY,
EXTRA VARCHAR (20),
TEL_EXTRA VARCHAR (15),
EXTRA_DIRECCION VARCHAR (15)
);

CREATE TABLE RBV_PAPEL (
CVE_PAPEL INT IDENTITY (5,15) PRIMARY KEY,
DESCRIPCION VARCHAR (20),
PAGO FLOAT (2),
EDAD INT
);

CREATE TABLE RBV_PELICULA (
CVE_PEL INT IDENTITY (10,10) PRIMARY KEY,
DESCRIPCION VARCHAR(20),
TIPO_PEL VARCHAR(20),
DURACION FLOAT (2)
);

CREATE TABLE RBV_ACTOR_PELICULA (
DNI_ACTOR INT,
CLAVE_PELICULA INT
);


INSERT INTO RBV_ACTOR_PRINCIPAL
VALUES ('Juana Pérez','56-57-20','Av 13'),
       ('Luis Gomez','14-34-12','Calle Zapotecas'),
       ('Maria Guzman','78-40-13','Periferico 123'),
       ('Pedro Juarez','77-34-90','Av 13');

INSERT INTO RBV_EXTRA
VALUES (5,'Ana Juarez','56-57-20','Av 20'),
       (2,'Luis Gomez','14-34-12','Calle Zapotecas'),
       (6,'Daniel Lopez','78-40-13','Sur 18'),
       (4, 'Pedro Juarez','77-34-90','Av 13');


INSERT INTO RBV_PAPEL
VALUES ('Protagonista', 10000, 20),
       ('Secundario', 80000, 21),
       ('De reparto', 50000, 19),
       ('Partes', 2500, 22),
       ('Protagonista', 2000, 23);

INSERT INTO RBV_PELICULA
VALUES ('EL FIN DEL MUNDO', 'ACCION', 3),
       ('EL REGRESO DE CHUKY', 'TERROR', 2),
       ('EL PAIS MARAVILLAS', 'FANTASIA', 2.5),
       ('MI SUEGRA', 'COMEDIA', 2.5);

	   SELECT * FROM RBV_PELICULA


INSERT INTO RBV_ACTOR_PELICULA
VALUES (1, 10),
       (2, 10),
       (3, 10),
       (4, 20),
       (5, 30),
       (6, 40),
       (1, 20),
       (5, 10),
       (6, 30);

	   SELECT*FROM RBV_ACTOR_PELICULA
	   SELECT*FROM RBV_ACTOR_PRINCIPAL
	   SELECT*FROM RBV_EXTRA
	   SELECT*FROM RBV_PAPEL
	   SELECT*FROM RBV_PELICULA

--MOSTRAR LA DESCRIPCION DE PELICULA Y LA DE PAPEL
	CREATE VIEW DJS_PAPEL AS(
	SELECT a.DESCRIPCION as pelicula, b.DESCRIPCION
	FROM RBV_PELICULA a, RBV_PAPEL b)

 --Nombre de actor principal y descripcion de pelicula
	CREATE VIEW DJS_ACTOR_DESCRIPCION_PELICULA AS(
		SELECT NOM_ACT_PRINCIPAL , DESCRIPCION
		FROM RBV_ACTOR_PELICULA, RBV_ACTOR_PRINCIPAL, RBV_PELICULA
		WHERE ID_ACT_PRINCIPAL = DNI_ACTOR AND CVE_PEL = CLAVE_PELICULA)

 -- nombre y direccion de los actores que solo son extras
 CREATE VIEW DJS_EXTRAS AS(
	SELECT EXTRA, EXTRA_DIRECCION
	FROM RBV_EXTRA
	EXCEPT
	SELECT NOM_ACT_PRINCIPAL, DOMICILIO
	FROM RBV_ACTOR_PRINCIPAL);

CREATE VIEW DJS_ACTORES AS(	
	SELECT*FROM RBV_ACTOR_PRINCIPAL
	UNION
	SELECT *FROM RBV_EXTRA);

create view DJS_ACTORES_PAPEL AS(
	SELECT NOM_ACT_PRINCIPAL,DESCRIPCION
	FROM DJS_ACTORES,RBV_PAPEL)

-- MOSTRAR TODOS LOS ACTORES, DOMICILIO, DESCRIPCIOM, TIPO_PEL, DURACION
	SELECT*FROM DJS_ACTORES

CREATE VIEW DJS_ACTORES_DOMICILIO_DATOS AS(
	SELECT NOM_ACT_PRINCIPAL, DOMICILIO, DESCRIPCION, TIPO_PEL, DURACION
	FROM DJS_ACTORES INNER JOIN RBV_ACTOR_PELICULA ON ID_ACT_PRINCIPAL=DNI_ACTOR INNER JOIN RBV_PELICULA ON CVE_PEL=CLAVE_PELICULA);

-- MOSTRAR TODOS LOS ACTORES Y LA DESCRIPCION DE PELICULA, LA CONSULTA SOLO DEBE HACER REFERENCIA A UNA TABLA
CREATE VIEW  DJS_ACTORES_DESCRIPCION_PELICULA AS(
	SELECT NOM_ACT_PRINCIPAL AS ACTORES, DESCRIPCION AS DESCRIPCION_PELICULA
	FROM DJS_ACTORES_DOMICILIO_DATOS)


SELECT*FROM DJS_ACTORES
SELECT*FROM DJS_ACTOR_DESCRIPCION_PELICULA
SELECT*FROM DJS_ACTORES_DOMICILIO_DATOS
SELECT*FROM DJS_ACTORES_PAPEL
SELECT*FROM DJS_EXTRAS
SELECT*FROM DJS_ACTORES_DESCRIPCION_PELICULA


