CREATE DATABASE DJS_LA_TIENDITA;
USE DJS_LA_TIENDITA;

CREATE TABLE DJS_ARTICULO (
	CVE_ARTICULO INT PRIMARY KEY NOT NULL,
	ARTICULO VARCHAR (15),
	PRECIO FLOAT (2),
	STOCK INT,
);

CREATE TABLE DJS_VENTA(
	CVE_VENTA INT PRIMARY KEY IDENTITY (2,2),
	FECHA_VENTA VARCHAR (15),
	HORA_VENTA VARCHAR (25),
);

CREATE TABLE DJS_DETALLE_VENTA_ARTICULO(
	CVE_VENTA_FK INT FOREIGN KEY REFERENCES DJS_VENTA (CVE_VENTA),
	CVE_ARTICULO_FK INT FOREIGN KEY REFERENCES DJS_ARTICULO (CVE_ARTICULO),
	CANTIDAD_ART INT
);

SELECT*FROM DJS_ARTICULO
SELECT*FROM DJS_VENTA
SELECT*FROM DJS_DETALLE_VENTA_ARTICULO

INSERT INTO DJS_ARTICULO (CVE_ARTICULO, ARTICULO, PRECIO, STOCK)
	VALUES	(1, 'AGUA EMBOT',8,15),
			(2, 'REFRESCO',12, 17),
			(3, 'PAPAS',10,5);

BEGIN TRY
	BEGIN TRAN
		UPDATE DJS_ARTICULO
		SET STOCK = STOCK-15
		WHERE CVE_ARTICULO=2
		INSERT INTO DJS_VENTA (FECHA_VENTA,HORA_VENTA)
		VALUES	(GETDATE(), SYSDATETIME())

		INSERT DJS_DETALLE_VENTA_ARTICULO (CVE_VENTA_FK,CVE_ARTICULO_FK,CANTIDAD_ART)
		VALUES (2, (SELECT CVE_ARTICULO FROM DJS_ARTICULO), 15)
		
		SELECT ARTICULO, PRECIO, STOCK, FECHA_VENTA, (PRECIO*CANTIDAD_ART) AS IMPORTE
		FROM DJS_ARTICULO INNER JOIN DJS_DETALLE_VENTA_ARTICULO ON CVE_ARTICULO =CVE_ARTICULO INNER JOIN DJS_VENTA ON CVE_VENTA=CVE_VENTA_FK
		WHERE CVE_VENTA=2

	
COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
END CATCH
	
	SELECT*FROM DJS_ARTICULO
