CREATE DATABASE DJS_EXAMEN_D;
use DJS_EXAMEN_D;

CREATE TABLE DJS_HOSPITAL (
CVE_HOS INT PRIMARY KEY,
NOM_HOS VARCHAR (20),
CIUDAD_HOS VARCHAR (20),
DIR_HOS VARCHAR (50),
TEL_HOS VARCHAR (10),
DIRECTOR VARCHAR (20) 
);

CREATE TABLE DJS_MEDICO (
ID_MED INT PRIMARY KEY,
NOM_MED VARCHAR (20),
DIR_MED VARCHAR (50),
ESPECIALIDAD VARCHAR (20),
EDAD_MED INT,
HOSPITAL1 INT FOREIGN KEY REFERENCES DJS_HOSPITAL(CVE_HOS)
);

CREATE TABLE DJS_PACIENTE (
ID_PAC INT PRIMARY KEY,
NOM_PAC VARCHAR (20),
DIR_PAC VARCHAR (50),
TEL_PAC VARCHAR (10),
EDAD_PAC INT
);

CREATE TABLE DJS_MEDICAMENTO (
CVE_MED INT PRIMARY KEY,
DESCRIPCION VARCHAR (20),
MARCA VARCHAR (20),
TAMAÑO VARCHAR (10),
GRAMOS INT,
);

CREATE TABLE DJS_SERVICIO (
CVE_SER INT PRIMARY KEY,
DESCRIPCION VARCHAR (20),
TIPO_SER VARCHAR (20),
COSTO FLOAT(2)
);

CREATE TABLE DJS_CONSULTA (
CVE_CON INT PRIMARY KEY,
HORA_CON VARCHAR (12),
IDN_MED INT FOREIGN KEY REFERENCES DJS_MEDICO(ID_MED),
IDENTIFICADOR_PAC INT FOREIGN KEY REFERENCES DJS_PACIENTE(ID_PAC),
SERVICIO INT FOREIGN KEY REFERENCES DJS_SERVICIO(CVE_SER)
);

CREATE TABLE DJS_CONSULTA_MEDICAMENTO (
CONSULTA1 INT FOREIGN KEY REFERENCES DJS_CONSULTA(CVE_CON),
MEDICAMENTO1 INT FOREIGN KEY REFERENCES DJS_MEDICAMENTO(CVE_MED)
);

SELECT * FROM DJS_HOSPITAL;
SELECT * FROM DJS_MEDICO;
SELECT * FROM DJS_PACIENTE;
SELECT * FROM DJS_MEDICAMENTO;
SELECT * FROM DJS_SERVICIO;
SELECT * FROM DJS_CONSULTA;
SELECT * FROM DJS_CONSULTA_MEDICAMENTO;

/*inciso b -instrucciones DDL*/
alter table DJS_MEDICAMENTO
add cant int;

alter table DJS_HOSPITAL
drop column DIR_HOS;

create view PACIENTE as(
SELECT NOM_PAC,EDAD_PAC
FROM  DJS_PACIENTE
WHERE NOM_PAC=1);

CREATE INDEX MEDICO
ON DJS_MEDICO (ID_MED,NOM_MED)

/*inciso C -instrucciones DML*/
insert DJS_HOSPITAL
values (1,'Hospital Juarez','CDMX','5511223344','Juan Perez')

update DJS_HOSPITAL
set TEL_HOS= 5566778899
where CVE_HOS=1;

SELECT NOM_PAC,EDAD_PAC AS MAXIMO
FROM  DJS_PACIENTE
WHERE EDAD_PAC=(select MAX(EDAD_PAC) from DJS_PACIENTE);

SELECT CVE_MED,cant AS MINIMO
FROM  DJS_MEDICAMENTO
WHERE cant=(select Min(cant) from DJS_MEDICAMENTO);

/*inciso D - 4 vistas multitabla*/
CREATE VIEW CV_DJS_PACIENTE_DJS_MEDICO_DJS_CONSULTA AS(
SELECT NOM_PAC,NOM_MED,CVE_CON 
FROM  DJS_PACIENTE,DJS_MEDICO,DJS_CONSULTA
WHERE IDENTIFICADOR_PAC=ID_PAC AND
ID_MED=IDN_MED);

CREATE VIEW CVE_DJS_MEDICO_DJS_HOSP_DJS_SERV AS(
SELECT NOM_MED,NOM_HOS,TIPO_SER,HORA_CON
FROM  DJS_MEDICO,DJS_HOSPITAL,DJS_SERVICIO,DJS_CONSULTA
WHERE ID_MED=IDN_MED AND
CVE_HOS=HOSPITAL1);

CREATE VIEW CV_DJS_PACIENTE_DJS_MEDICO_DJS_CONSULTA_DJS_HOS_DJS_SERV AS(
SELECT NOM_PAC,NOM_MED,NOM_HOS,TIPO_SER,HORA_CON
FROM  DJS_PACIENTE,DJS_MEDICO,DJS_CONSULTA,DJS_HOSPITAL,DJS_SERVICIO
WHERE IDENTIFICADOR_PAC=ID_PAC AND
ID_MED=IDN_MED AND
CVE_HOS=HOSPITAL1 AND
CVE_SER=SERVICIO
);

CREATE VIEW CV_DJS_PACIENTE_DJS_MEDICO_DJS_CONSULTA_DJS_CONSLTA_MED AS(
SELECT NOM_PAC,NOM_MED,CVE_CON,CVE_MED
FROM  DJS_PACIENTE,DJS_MEDICO,DJS_CONSULTA,DJS_CONSULTA_MEDICAMENTO,DJS_MEDICAMENTO
WHERE IDENTIFICADOR_PAC=ID_PAC AND
ID_MED=IDN_MED AND
CVE_MED=MEDICAMENTO1 AND
CVE_CON=CONSULTA1
);

SELECT * FROM CV_DJS_PACIENTE_DJS_MEDICO_DJS_CONSULTA_DJS_CONSLTA_MED;
SELECT * FROM CV_DJS_PACIENTE_DJS_MEDICO_DJS_CONSULTA_DJS_HOS_DJS_SERV;
SELECT * FROM CVE_DJS_MEDICO_DJS_HOSP_DJS_SERV;
SELECT * FROM CV_DJS_PACIENTE_DJS_MEDICO_DJS_CONSULTA;



/*inciso - crear un usario*/


